#!/usr/bin/env bash

# vi: ft=bash
set -euo pipefail

CMD=$(prj-private-cli.py "$(basename $0)" "$@" <<EOF
short="-b", long="--base", dest="BASE", type="str", default="", help="Which base directory to use"
long="--all", dest="ALL", type="FLAG", default=False, help="Ignore the .prjignore"
long="--cpus", dest="CPUS", type=int, default=2, help="What's the maximum number of CPUs we can use? Use -1 for all."
dest="TARGET", type=str, nargs="*", help="Only check these files"
EOF
)

if ! (echo "${CMD}" | grep '^### prj-private-cli output$' > /dev/null)
then
    # help or an error occurred
    echo "# $(basename $0)"
    echo "${CMD}"
    exit 0
fi

eval "${CMD}"

if [ -z "${BASE:-}" ]
then
    BASE="$(prj-private-findbase.sh "${PWD}" 2> /dev/null)" || :
else
    BASE="$(prj-private-findbase.sh "${BASE}" True 2> /dev/null)" || :
fi


cd "${BASE}"

if [ "${ALL:-}" == "True" ] || [ ! -e "${BASE}/.prjignore" ]
then
    BKPIGNORE=""
else
    BKPIGNORE=$(cat "${BASE}/.prjignore")
fi


FILES=$(find "${BASE}" -type f,l | awk -v DIR="${BASE}" '{print substr($0, length(DIR) + 2)}')

if [ ! -z "${BKPIGNORE:-}" ] && [ ! -z "${FILES:-}" ]
then
    FILES=$(echo "${FILES}" | (grep --no-filename --invert-match -f <(echo "${BKPIGNORE}") || : ))
fi

if [ "${#TARGET[@]}" -gt 0 ] && [ ! -z "${FILES:-}" ]
then
    FILES=$(echo "${FILES}" | (grep --no-filename -f <(printf "%s\n" "${TARGET[@]}") || : ))
fi

if [ -z "${FILES:-}" ]
then
    exit 0
fi

[ "${CPUS}" -gt 0 ] && PROC_PARAM="--max-procs=${CPUS}" || PROC_PARAM=""

echo "${FILES}" \
    | xargs ${PROC_PARAM} -I {} sha256sum {} \
    | sort -k 2
